# Generated by Django 2.2.2 on 2019-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField()),
                ('status', models.CharField(default='off', max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Buttons',
        ),
    ]
