# Generated by Django 2.2.2 on 2019-08-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_control', '0003_auto_20190806_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
