# Generated by Django 2.2.2 on 2019-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_control', '0004_auto_20190806_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='product_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
